SUPABASE_URL = "https://ahgdcchhzckavbrkacrk.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFoZ2RjY2hoemNrYXZicmthY3JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNzM1MDQsImV4cCI6MjA2MjY0OTUwNH0.hsFAEPjk3_dgovmQzzKdM3jDiV9N_CB355TWdK5zGc4"

